### ISSUE TITLE
Triggering execution on small enemies like skeever or goblins can cause enemy to become invincible

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#68] opened 2023-05-18 20:15 UTC
When attacking skeever or goblins it does this animation that doesn't kill them

**Comment by zediious** [comment] 2023-05-21 20:17
I believe I have this fixed for the next version, but I will need to extensively test with a large amount of small animals to ensure the issue is gone before I mark this fixed :)

**Comment by zediious** [comment] 2023-05-22 19:47
This issue is fixed by removing zxlice's Backstab and Parry (caused the issue for NPCs other than Skeever, just not as often) and disabling Creature killmoves in Violens MCM.

**Closed** 2023-05-22 22:56 UTC
Labels: bug, fixed
